# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hello/32-Bit-ALU/32-Bit-ALU.cache/wt [current_project]
set_property parent.project_path /home/hello/32-Bit-ALU/32-Bit-ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/hello/32-Bit-ALU/32-Bit-ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/GenProp.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/arithmeticRightShift.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/bitwiseAND.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/bitwiseNOT.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/bitwiseOR.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/bitwiseXOR.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/equalTo.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/fastAdder32.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/fastAdder4.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/leftShift.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/lessThan.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/logicalLeftShift.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/logicalRightShift.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/multiplier32.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/mux2.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/subtractor32.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/twoscomplement.v
  /home/hello/32-Bit-ALU/32-Bit-ALU.srcs/sources_1/new/main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
